name: Upload to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    environment:
      name: pypi.org
      url: https://pypi.org/project/pytest-boilerplate/

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
    - name: Package project
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload distributions
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
